Allow a device to be assigned to application
flowforge/flowforge-device-agent pull request #161
Opened 2023-08-20 20:45 UTC by Steve-Mcl

## Description

Permit a device to be assigned to an application.

NOTE: Raised in draft to permit other engineers to test - before writing a whole bunch of tests and updating docs.

Notable:
1. permit the agent to start even if the working dir does not exist. Instead of a hard exit, an attempt to generate the working directory is made.
2. adds `currentApplication` which when set, permits the device to launch node-red - allowing user to modifiy flows.
3. updates the log output to indicate instance or application as device owner
4. only writes necessary parts to file - to prevent the fake application snapshot overwriting users flows edits

#### Application level device implementation:
 - Developer Mode / Remote Access ✅
 - Device Logs ✅
 - Team Library ✅
 - Theme, device name and NR menu links ✅
 - Adding device in application view adds device to application ✅
 - Newly added device in application view updates status when config is applied to device and it starts up ✅
 - Upload Snapshot ❌
 - Download Snapshot ❌
 - Project Links ❌
 - Grouping and settings ❌

#### TODO (this iteration):
 - tests
 - docs
 - manual testing combinations - to ensure there are no issues when running older platform with newer agent and vice versa
  
#### TODO (next iteration)
 - Support snapshots (upload/download)
 - Support grouping
 - Group settings (env/modules/etc)
 - Project Links (Device links? Concept?)

## Related Issue(s)

[Devices to be assigned to an Application, without being assigned to an Instance#2619](https://github.com/flowforge/flowforge/issues/2619)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-08-24 17:01 UTC, knolleary requested changes
Some initial comments... not got through everything yet.

2023-08-24 17:01 UTC, knolleary commented on README.md
> +This module provides an agent that runs Node-RED deployed from the platform.
```suggestion
This module provides an agent that runs Node-RED instances deployed from the
FlowForge platform.
```

From a plain English POV, I'd keep this as-is. This is about running instances of Node-RED. Also 'the platform' isn't obvious - given this is the first line of the readme.

2023-08-24 17:01 UTC, knolleary commented on index.js
> +        try {
This is a seemingly unrelated change in behaviour of the device agent - ideally would be a separate PR. The readme says the directory must exist. If that is no longer the case, then it needs to be updated.

2023-08-24 17:01 UTC, knolleary commented on lib/agent.js
> +            info('  * Snapshot           : 0 (Application Mode)') // TODO: remove this when we have a better solution for snapshots on devices at application level
```suggestion
            info('  * Snapshot           : none') // TODO: remove this when we have a better solution for snapshots on devices at application level
```

'Application Mode' isn't a defined thing anywhere. We already have 'Operation mode' and 'Developer mode' ... too many modes.

2023-08-24 17:09 UTC, knolleary commented
In relation to the discussion on https://github.com/flowforge/flowforge/pull/2621#discussion_r1304446272 , I can see a possible future where the valid states will be.

Assigned To | Application | Instance
-------------|------------|----------
_nothing_     | _null_         | _null_
Application | `<applicationId>`          | _null_
Instance   | `<applicationId>`             | `<instanceId>`

Meaning, the presence of `application` means its assigned to _something_, and `instance` tells you if it is a specific instance or not.

In quite a few places with this PR there is pieces of logic similar to:

```
(this.currentApplication ? 'application' : (this.currentProject ? 'project' : 'none'))
```

Which puts all the weight on whether application is set or not. That matches up with the current implementation of the platform, but would make it harder **if** we decide to modify the model as I've described.

I *think* we could safely flip the logic in the device agent to something like:

```
this.currentProject ? ' project' : (this.currentApplication ? 'application' : 'none'))
```

I believe that would still behave the same way with the current server implementation, but would also work *if* we modified things.

Given how many places that bit of logic exists in this PR, I don't know if the logic is sound - but wanted to get your input if this is feasible?

2023-08-29 13:21 UTC, Steve-Mcl commented on index.js
> +        try {
When developing this, I needed to spin up multipe devices on demand and added this to ease it. 

I forgot I left it in but now it is - I would really prefer to leave it in as it is both user useful and much more user friendly than an error message and failed start.

I will update the docs to reflect this - but I can just as easily remove it if insisted upon.

2023-08-29 13:28 UTC, Steve-Mcl commented on index.js
> +        try {
docs updated in [c849697](https://github.com/flowforge/flowforge-device-agent/pull/161/commits/c84969721d1ee0c4c9d4b1457cb598f54fa4b9df)

2023-08-29 13:31 UTC, Steve-Mcl commented
> Looking at that line of code above, it puts all the weight on whether application is set or not. That matches up with the current implementation of the platform, but would make it harder **if** we decide to modify the model as I've described.
> 
> I _think_ we could safely flip the logic in the device agent to something like:
> 
> ```
> this.currentProject ? ' project' : (this.currentApplication ? 'application' : 'none'))
> ```
> 
> I believe that would still behave the same way with the current server implementation, but would also work _if_ we modified things.
> 
> Given how many places that bit of logic exists in this PR, I don't know if the logic is sound - but wanted to get your input if this is feasible?

The order of the logic was deliberate and considered but I also understand your point.

I will go through both ends again and determine the side-effects of changing (if any).

Watch this space.

2023-08-29 15:21 UTC, Steve-Mcl commented
> > I _think_ we could safely flip the logic in the device agent to something like:
> > ```
> > this.currentProject ? ' project' : (this.currentApplication ? 'application' : 'none'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe that would still behave the same way with the current server implementation, but would also work _if_ we modified things.
> > Given how many places that bit of logic exists in this PR, I don't know if the logic is sound - but wanted to get your input if this is feasible?
> 
> The order of the logic was deliberate and considered but I also understand your point.
> 
> I will go through both ends again and determine the side-effects of changing (if any).

Login order changed in [1026df4](https://github.com/flowforge/flowforge-device-agent/pull/161/commits/1026df47c6403bed7033a435cadd158e5e36e57c) and verified locally.

It did throw up an issue which has also been resolved on the platform repo.

Ready for re-review now.

2023-08-30 08:15 UTC, knolleary approved these changes

2023-08-30 08:15 UTC, merged